import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface ContentRequest {
  type: string;
  prompt: string;
  tone: string;
  context?: string;
}

function generateBlog(prompt: string, tone: string): string {
  return `# ${prompt}

*Published on AdvutAI Content Studio | Tone: ${tone}*

---

In today's rapidly evolving landscape, understanding **${prompt.toLowerCase()}** has become essential for professionals and organizations alike. This article explores the key dimensions and provides actionable insights you can apply today.

## The Current State

The world of ${prompt.toLowerCase()} is experiencing a fundamental shift. What was once a niche concern has become a mainstream priority, driven by three converging forces:

1. **Technology acceleration** — New tools and platforms are enabling capabilities that were impossible just two years ago
2. **Market demand** — Users and customers now expect sophisticated, seamless experiences as a baseline
3. **Competitive pressure** — Organizations that adapt quickly gain disproportionate advantages

## Key Insights

### Insight #1: The Fundamentals Still Matter

Before chasing trends, ensure your foundation is solid. The organizations seeing the best results from ${prompt.toLowerCase()} are those that invested in:

- **Clear strategy** — Knowing what you're optimizing for prevents wasted effort
- **Quality data** — Garbage in, garbage out applies to every domain
- **Team alignment** — Shared understanding beats individual brilliance

### Insight #2: Execution Beats Perfection

The biggest mistake we see isn't getting things wrong — it's not shipping at all. The most successful implementations share these traits:

- **MVP-first approach** — Launch with core value, iterate based on real feedback
- **Measurement framework** — Define success metrics before you start
- **Rapid iteration cycles** — Weekly improvements compound dramatically over quarters

### Insight #3: The Human Element Is Non-Negotiable

Technology enables, but people deliver. The best tools in the world fail without:

- **User adoption** — Build for your actual users, not your ideal ones
- **Skill development** — Invest in training alongside tooling
- **Change management** — Communicate the why, not just the what

## Practical Framework

Here's a framework you can apply immediately:

\`\`\`
Step 1: Audit    →  Where are you now? (1 week)
Step 2: Plan     →  Where do you want to be? (2 weeks)
Step 3: Build    →  Create the minimum viable solution (4 weeks)
Step 4: Measure  →  Track against your defined metrics (ongoing)
Step 5: Iterate  →  Improve based on real data (2-week cycles)
\`\`\`

## What's Next

The trajectory is clear: ${prompt.toLowerCase()} will continue to grow in importance. The question isn't whether to invest — it's how quickly you can start seeing returns.

**Three things to do this week:**
1. Assess your current state honestly
2. Identify the single highest-impact improvement
3. Commit to a 2-week sprint to implement it

---

*This article was generated by AdvutAI Content Studio. Want a version tailored to your specific audience or industry? Let us know.*`;
}

function generateEmail(prompt: string, tone: string): string {
  return `**Subject:** ${prompt}

---

Dear [Recipient Name],

I hope this finds you well. I'm reaching out regarding **${prompt.toLowerCase()}** and wanted to share some thoughts that I believe will be valuable for our next steps.

## Context

After reviewing the current situation, I've identified several key areas where we can make meaningful progress:

1. **Immediate opportunity** — There's a clear path to [specific outcome] that we can pursue right now with minimal investment
2. **Strategic alignment** — This initiative aligns directly with our [quarterly/annual] objectives around [goal area]
3. **Competitive advantage** — Acting now positions us ahead of the curve while others are still evaluating

## Proposal

I'd like to propose the following approach:

**Phase 1 (Week 1-2):** Discovery and alignment
- Review current state and identify quick wins
- Align stakeholders on objectives and success metrics
- Establish communication cadence

**Phase 2 (Week 3-6):** Implementation
- Execute on the highest-impact items first
- Weekly progress reviews with key stakeholders
- Iterate based on early feedback

**Phase 3 (Ongoing):** Optimization
- Measure results against defined KPIs
- Scale what works, cut what doesn't
- Share learnings across the team

## Ask

I'd appreciate 30 minutes this week to discuss this in more detail. I'm confident that with the right focus, we can see meaningful results within the first month.

Would **Tuesday or Thursday afternoon** work for a brief call?

Best regards,
[Your Name]

---

*Generated by AdvutAI Content Studio | Tone: ${tone}*`;
}

function generateSocial(prompt: string, tone: string): string {
  return `## Social Media Posts for: ${prompt}

---

### Post 1 — Hook/Thought Leadership
${prompt} is changing faster than most people realize.

Here's what nobody is talking about:

The fundamentals haven't changed — but the execution gap is widening.

Those who nail the basics AND leverage new tools are pulling ahead at an unprecedented rate.

The good news? It's not too late to catch up.

Here's where to start ↓

### Post 2 — Value/How-To
3 things I wish I knew about ${prompt.toLowerCase()} sooner:

1. Start with strategy, not tools
   → Define your outcome before choosing your approach

2. Measure what matters, not what's easy
   → Vanity metrics feel good. Business metrics pay bills.

3. Iteration beats perfection
   → Ship weekly. Improve daily. Rest on Sundays.

Save this for your next planning session.

### Post 3 — Engagement/Question
Hot take: Most ${prompt.toLowerCase()} advice is outdated within 6 months.

The only things that stay constant:
✓ Clear thinking
✓ Fast execution
✓ Real user feedback

What's the one principle that's stayed true for you?

Drop it in the replies 👇

---

*Generated by AdvutAI Content Studio | Tone: ${tone}*`;
}

function generateMarketing(prompt: string, tone: string): string {
  return `# Marketing Copy: ${prompt}

---

## Hero Headlines (A/B Test Ready)

**Option A:** "Master ${prompt} — Before Your Competitors Do"
**Option B:** "The ${prompt} Advantage You've Been Missing"
**Option C:** "Stop Guessing. Start Winning at ${prompt}."

## Value Proposition

Transform how you approach **${prompt.toLowerCase()}**. Our solution delivers measurable results in weeks, not months — with the simplicity your team needs and the power your business demands.

## Key Benefits

| Benefit | Before | After |
|---------|--------|-------|
| Speed | Weeks to implement | Days to deploy |
| Cost | High upfront investment | Predictable monthly pricing |
| Results | Hope-based | Data-driven |
| Scale | Manual bottleneck | Automated growth |

## Social Proof

> "We saw a 3x improvement in our ${prompt.toLowerCase()} outcomes within the first 30 days. The ROI was undeniable." — VP of Strategy, Fortune 500

## Feature Highlights

- **Smart Automation** — Eliminate repetitive tasks and focus on high-impact work
- **Real-Time Analytics** — Know exactly what's working and what to change
- **Team Collaboration** — Built for teams that move fast together
- **Enterprise Security** — SOC 2 compliant with role-based access

## Call to Action

**Primary CTA:** "Start Free Trial" → No credit card required
**Secondary CTA:** "Book a Demo" → 15-minute personalized walkthrough
**Urgency CTA:** "Limited Time: Get 30% off your first 3 months"

## Email Subject Line Options

1. "The ${prompt} edge your competitors don't want you to know about"
2. "3 reasons teams are switching their ${prompt.toLowerCase()} approach"
3. "[First Name], your ${prompt.toLowerCase()} strategy needs an upgrade"

---

*Generated by AdvutAI Content Studio | Tone: ${tone}*`;
}

function generateReport(prompt: string, tone: string): string {
  return `# Strategic Report: ${prompt}

**Classification:** Internal — Executive Review
**Date:** ${new Date().toISOString().split('T')[0]}
**Prepared by:** AdvutAI Research Division

---

## Executive Summary

This report presents a comprehensive analysis of **${prompt.toLowerCase()}**, including market dynamics, strategic implications, and actionable recommendations for leadership review.

**Key Finding:** The landscape for ${prompt.toLowerCase()} is at an inflection point. Organizations that act within the next 90 days will gain a significant first-mover advantage.

## Market Context

### Current State
- Market size: Estimated $XXB globally (2025)
- Growth rate: 18-25% CAGR
- Key drivers: Digital transformation, regulatory changes, competitive pressure
- Primary barriers: Skills gap, legacy infrastructure, organizational inertia

### Competitive Landscape
- **Leaders** (2-3 players): Established with strong market position
- **Challengers** (4-5 players): Growing rapidly with innovative approaches
- **Emerging** (10+ players): Niche solutions targeting specific verticals

## Strategic Analysis

### SWOT Assessment

| | Positive | Negative |
|---|----------|----------|
| **Internal** | **Strengths:** Strong technical foundation, experienced team, existing customer base | **Weaknesses:** Limited brand awareness, small team, constrained budget |
| **External** | **Opportunities:** Growing market, underserved segments, technology advances | **Threats:** Well-funded competitors, market consolidation, regulatory uncertainty |

### Risk Assessment

| Risk | Probability | Impact | Mitigation |
|------|------------|--------|------------|
| Competitive entry | High | High | Accelerate unique value proposition |
| Technical complexity | Medium | Medium | Invest in expertise and tooling |
| Market timing | Medium | High | Phased approach with early validation |
| Resource constraints | High | Medium | Prioritize ruthlessly, outsource non-core |

## Recommendations

### Immediate Actions (0-30 days)
1. Complete competitive audit and gap analysis
2. Validate core assumptions with 5-10 target customers
3. Define MVP scope and success metrics

### Short-Term (30-90 days)
4. Launch MVP with targeted early adopters
5. Establish feedback loops and measurement framework
6. Begin building thought leadership content

### Medium-Term (90-180 days)
7. Scale based on validated learnings
8. Expand feature set based on user demand
9. Explore strategic partnerships

## Resource Requirements

| Category | Q1 | Q2 | Q3 |
|----------|-----|-----|-----|
| Engineering | 3 FTE | 5 FTE | 5 FTE |
| Design | 1 FTE | 2 FTE | 2 FTE |
| Marketing | 1 FTE | 2 FTE | 3 FTE |
| Budget | $XXk | $XXk | $XXk |

## Next Steps

- [ ] Leadership review and approval (this week)
- [ ] Team alignment meeting (next week)
- [ ] Sprint planning for Phase 1 (following week)

---

*This report was generated by AdvutAI Content Studio. Data should be validated with primary research before strategic decisions.*`;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const body: ContentRequest = await req.json();
    const { type, prompt, tone = "professional" } = body;

    if (!prompt || typeof prompt !== "string") {
      return new Response(
        JSON.stringify({ error: "Prompt is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const generators: Record<string, (p: string, t: string) => string> = {
      blog: generateBlog,
      email: generateEmail,
      social: generateSocial,
      marketing: generateMarketing,
      report: generateReport,
    };

    const generator = generators[type] || generateBlog;
    const content = generator(prompt, tone);

    return new Response(
      JSON.stringify({ content }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Internal server error";
    return new Response(
      JSON.stringify({ error: msg }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
