import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface ContentRequest {
  type: string;
  prompt: string;
  tone: string;
  context: string;
}

const TEMPLATES: Record<string, (prompt: string, tone: string) => string> = {
  blog: (prompt, tone) => `# ${prompt}

In today's rapidly evolving landscape, understanding ${prompt.toLowerCase()} has become more important than ever. This article explores the key aspects and provides actionable insights.

## The Current Landscape

The world of ${prompt.toLowerCase()} is undergoing significant transformation. Organizations and individuals alike are recognizing the need to adapt and evolve their approaches.

## Key Considerations

1. **Understanding the fundamentals** — Before diving deep, it's essential to grasp the core concepts that underpin ${prompt.toLowerCase()}.

2. **Practical applications** — Theory without practice is incomplete. Here's how you can apply these concepts in real-world scenarios.

3. **Future outlook** — What trends are shaping the future? Staying ahead requires anticipation and preparation.

## Best Practices

- Start with a clear strategy and defined goals
- Measure progress with meaningful metrics
- Iterate and refine your approach based on results
- Stay informed about the latest developments

## Conclusion

${prompt} represents both a challenge and an opportunity. By approaching it with the right mindset and tools, you can unlock significant value and drive meaningful outcomes.

---

*Written by AdvutAI Content Studio in a ${tone} tone*`,

  email: (prompt, tone) => `Subject: ${prompt}

Dear [Recipient],

I hope this message finds you well. I'm writing to discuss ${prompt.toLowerCase()}.

[Main content paragraph - adapt based on your specific needs]

I believe this presents an excellent opportunity for [desired outcome]. The key benefits include:

- **Benefit 1**: [Description]
- **Benefit 2**: [Description]
- **Benefit 3**: [Description]

I'd love to discuss this further at your convenience. Would you be available for a brief call this week?

Please don't hesitate to reach out if you have any questions or need additional information.

Best regards,
[Your Name]

---
*Generated by AdvutAI Content Studio in a ${tone} tone*`,

  social: (prompt, tone) => {
    const posts = [
      `Excited to share insights on ${prompt}! Here's what I've learned:\n\n1. The fundamentals matter more than flashy tactics\n2. Consistency beats intensity\n3. Data-driven decisions win\n\nWhat's your take? 👇`,
      `Just published: Everything you need to know about ${prompt}\n\nTL;DR:\n- It's changing fast\n- The basics still work\n- Adaptation is key\n\nRead the full breakdown in my latest article.`,
      `Hot take on ${prompt}:\n\nMost people overcomplicate it. The secret? Focus on these 3 things:\n\n1. Clear strategy\n2. Consistent execution\n3. Continuous learning\n\nSimple, not easy.`,
    ];
    return posts[Math.floor(Math.random() * posts.length)] + `\n\n---\n*Generated by AdvutAI Content Studio in a ${tone} tone*`;
  },

  marketing: (prompt, tone) => `# ${prompt}

## Headline Options
1. "Transform Your Approach to ${prompt}"
2. "The Complete Guide to ${prompt}"
3. "Unlock the Power of ${prompt}"

## Value Proposition
Discover how ${prompt.toLowerCase()} can revolutionize your workflow, boost productivity, and deliver measurable results.

## Key Benefits
- **Save Time**: Automate and streamline your processes
- **Increase Quality**: Deliver better outcomes with less effort
- **Scale Effectively**: Grow without proportional cost increases
- **Stay Competitive**: Keep pace with industry leaders

## Call to Action
Ready to transform how you approach ${prompt}? Get started today and see results within the first week.

## Social Proof
> "Implementing these strategies for ${prompt.toLowerCase()} changed our entire approach. Results exceeded expectations." — Industry Leader

---
*Generated by AdvutAI Content Studio in a ${tone} tone*`,

  report: (prompt, tone) => `# ${prompt} — Strategic Report

## Executive Summary
This report provides a comprehensive analysis of ${prompt.toLowerCase()}, including current trends, challenges, opportunities, and strategic recommendations.

## Methodology
Our analysis combines quantitative data analysis, industry expert interviews, and competitive benchmarking to deliver actionable insights.

## Findings

### 1. Current State
The landscape for ${prompt.toLowerCase()} is characterized by rapid evolution and increasing complexity. Key indicators show:

- Market growth: 15-25% annually
- Adoption rate: Accelerating across sectors
- Investment levels: Record highs in 2024-2025

### 2. Opportunities
- **Emerging markets**: Significant untapped potential
- **Technology integration**: New tools enable better outcomes
- **Cross-sector applications**: Expanding use cases
- **Talent development**: Growing expertise pool

### 3. Risks
- Regulatory changes could impact operations
- Market saturation in mature segments
- Technology disruption requiring continuous adaptation

## Recommendations
1. Invest in foundational capabilities
2. Build strategic partnerships
3. Develop talent and expertise
4. Maintain agility in approach
5. Monitor and measure outcomes continuously

## Next Steps
- Review findings with key stakeholders
- Prioritize recommendations based on organizational capacity
- Develop implementation timeline
- Establish success metrics

---
*Generated by AdvutAI Content Studio in a ${tone} tone*`,
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const body: ContentRequest = await req.json();
    const { type, prompt, tone = "professional" } = body;

    if (!prompt || typeof prompt !== "string") {
      return new Response(
        JSON.stringify({ error: "Prompt is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const generator = TEMPLATES[type] || TEMPLATES.blog;
    const content = generator(prompt, tone);

    return new Response(
      JSON.stringify({ content }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Internal server error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
