import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface ResearchRequest {
  query: string;
  reportId: string;
}

function generateResearchReport(query: string) {
  const sources = [
    { title: "Wikipedia - " + query, url: "https://en.wikipedia.org/wiki/" + encodeURIComponent(query), type: "encyclopedia" },
    { title: "Academic Papers on " + query, url: "https://scholar.google.com/scholar?q=" + encodeURIComponent(query), type: "academic" },
    { title: "Industry Report: " + query, url: "https://www.example.com/reports/" + encodeURIComponent(query), type: "report" },
    { title: "Technical Documentation", url: "https://docs.example.com/" + encodeURIComponent(query), type: "documentation" },
    { title: "News Analysis: " + query, url: "https://news.example.com/" + encodeURIComponent(query), type: "news" },
  ];

  const summary = `Based on comprehensive analysis of multiple sources regarding "${query}", here are the key findings:

**Overview**: ${query} is a significant topic with wide-ranging implications across multiple domains.

**Key Findings**:
1. The subject has seen substantial development in recent years
2. Multiple perspectives exist among experts and practitioners
3. Current trends indicate continued growth and evolution
4. Several challenges remain to be addressed
5. Opportunities for innovation are emerging

**Recommendations**: Further research is recommended to explore the specific aspects most relevant to your use case.`;

  const report_content = `# Research Report: ${query}

## Executive Summary

${summary}

## Introduction

This report presents a comprehensive analysis of "${query}", drawing from multiple authoritative sources across academic, industry, and technical domains.

## Background

The topic of ${query} has gained significant attention in recent years. Understanding its fundamentals is crucial for making informed decisions.

## Key Analysis

### Current State
- The field is experiencing rapid development
- New methodologies and approaches are emerging
- Cross-disciplinary applications are expanding
- Standardization efforts are underway

### Market Trends
- Growing adoption across industries
- Increasing investment in research and development
- Shift toward more accessible and scalable solutions
- Integration with existing workflows and systems

### Technical Considerations
- Performance optimization remains a priority
- Security and compliance requirements are evolving
- Interoperability standards are being established
- Cost-effectiveness is improving

### Challenges
- Complexity of implementation in legacy systems
- Need for specialized expertise
- Regulatory compliance across jurisdictions
- Balancing innovation with stability

## Sources

${sources.map((s, i) => `${i + 1}. [${s.title}](${s.url}) - ${s.type}`).join('\n')}

## Conclusion

The analysis of ${query} reveals a dynamic and evolving landscape. Organizations should consider both the opportunities and challenges when developing their strategy. Staying informed about the latest developments and maintaining flexibility in approach will be key to success.

---
*Report generated by AdvutAI Research Agent*`;

  return { summary, sources, report_content };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const body: ResearchRequest = await req.json();
    const { query } = body;

    if (!query || typeof query !== "string") {
      return new Response(
        JSON.stringify({ error: "Query is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const result = generateResearchReport(query);

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Internal server error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
